### ISSUE TITLE
Error: CentOS- is not supported

### ISSUE THREAD

**Issue by tommy-muehle** [jfryman/puppet-selinux#52]
Hi,

we get the error 
```
Error: CentOS- is not supported at /tmp/vagrant-puppet/modules-f9727779af741867e6222f127e22141c/selinux/manifests/params.pp:35
```
on puppet provisioning in [this](https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.0.0/centos-6.6-x86_64.box) box. (CentOS 6.6)

It seems the ``` ${::operatingsystemmajrelease} ``` variable are empty.

Used versions:
```
puppet --version
3.8.2

vagrant --version
Vagrant 1.7.2

VirtualBox: 4.3.28
```

Sincerly, Tommy

**Comment by gregswift** [comment]
what version of facter?

**Comment by tommy-muehle** [comment]
The facter version is "2.4.4".

**Comment by A13x3i** [comment]
Same problem with 2.4.4 version of facter , however version is defined
facter operatingsystemmajrelease
6

**Comment by A13x3i** [comment]
Ok I think I might have a solution for this one make sure you have the latest module from github
check the params.pp file it should have the following lines
```
34,40d33
<             '': {
<               # Fallback to lsbmajdistrelease, if puppet version is < 3.0
<               if($::lsbmajdistrelease == 5) {
<                 $sx_fs_mount = '/selinux'
<                 $package_name = 'policycoreutils'
<               }
<             }
```
if it doesn't you can copy them there it it will all work.
I think the problem is  hat jfryman-selinux is not up to date on puppet forge e.g 
```
# bundle exec librarian-puppet show | grep selinux
jfryman-selinux (0.2.5)
```
does not contain commit https://github.com/jfryman/puppet-selinux/commit/646bfb83ab5b6788d188a00b162a77490903b4e9

**Comment by gregswift** [comment]
good catch.  i kept looking at the code confused as to why that wasnt working. 

still, even on puppet 2 i thought that  variable would exist with the right version of face
