### ISSUE TITLE
Move to selmodule/selboolean for selinux::module/boolean?

### ISSUE THREAD

**Issue by jyaworski** [jfryman/puppet-selinux#70]
Hello:

It looks like puppet has support for selmodule and selboolean types.

https://docs.puppetlabs.com/references/latest/type.html#selboolean

https://docs.puppetlabs.com/references/latest/type.html#selmodule

Should we modify the existing classes for these to take advantage of the built-in types?

**Comment by earsdown** [comment]
-9999 for this idea.

1. This change is not backward compatible.
2. You've just broken systems that depend on previous functionality (like selinux::module's use_makefile parameter that disappeared without warning).
3. If we wanted to use native types, we would be using one of the other selinux modules (there are many). Instead, we're using this module because we find it's better than using the native types. Which I thought was rather obvious.

If you really want to do this, consider publishing it under a different module name. If you can't revert this change and restore previous behavior, please consider putting a gigantic notice in the README warning users not to depend on this module for anything remotely important.

**Comment by jyaworski** [comment]
Hello:

This was solved in #73. Native types only install the compiled .pp files for selmodule.

Closing issue.
