### ISSUE TITLE
selinux::module works only if module name contains local_ by default

### ISSUE THREAD

**Issue by toddnni** [jfryman/puppet-selinux#90]
The default prefix local_ is prefixed to module name
```
selmodule { "${prefix}${name}":
```
but this default is unintuitive. For example in the provided example
```
selinux::module{ 'apache':
  ensure => 'present',
  source => 'puppet:///modules/selinux/apache.te',
}
```
the module name inside apache.te must be
```
module local_apache 1.0;
```
so that next run finds the module from `semodule --list`.

If one provides a name
```
module apache 1.0;
```
in the file, then the module will be installed with name apache and selmodule tries to search for local_apache. As it doesn't find the module, it will reinstall the module on every run.

If the idea is to prefix module files in selmoduledir, we should change
```
selmodule { "${prefix}${name}":
  ensure       => $ensure,
  selmoduledir => $sx_mod_dir,
  syncversion  => $syncversion,
}
```
to
```
selmodule { "${name}":
  ensure       => $ensure,
  selmodulepath => "${sx_mod_dir}/${prefix}${name}",
  syncversion  => $syncversion,
}
```
in module.pp

**Comment by toddnni** [comment]
The change I proposed is not backward compatible, but I argue that the new solution is easier to use.

**Comment by jfryman** [comment]
@toddnni Did you happen to do an upgrade, or are you starting from scratch with this new code path? This is the right thing to do, but I would like to get a better understanding for what existing users might expect if this gets merged. Convergence makes everything ok, or is a bad time ahead for users?

**Comment by toddnni** [comment]
We have used the module for a while but we migrated from spiette/puppet-selinux without touching the modules (they were named like apache instead of local_apache). Module installation worked fine, but I noticed that now it reinstalls the selinux modules on every run, because module's name apache doesn't match ${prefix}apache.

So things won't be ok if user has named modules like local_apache.

**Comment by ncsutmf** [comment]
This might fix an issue we noticed that occurs when upgrading the version of this puppet module on RHEL 7 from an older one from before the switch to the use of the Makefile and the addition of the prefix.  We kept getting puppet errors because the semodule could not be loaded (even though it was already loaded w/o the prefixed name) due to the fact that Makefile is not there by default in RHEL 7 (see #88).

I am guessing the addition of the prefix was to prevent name collisions with semodules that get installed by default?  But if internally the module is still named without the prefix, are we still getting a name collision?

For example if I were to name a semodule cups with a version of 1.0.0.  I see from `semodule --list` under RHEL 7.2 that there is a cups 1.16.2 already listed.  I assume this was added by the cups package or built in to selinux.  Would my custom module that adds something that was missing from the existing one even install?  If it does would it replace the pre-existing one?  What happens if I set the version of my custom one to 1.17.0?

**Comment by toddnni** [comment]
@ncsutmf: This Puppet module doesn't handle the internal module naming, and I guess that in your scenario the custom cups module would overwrite the original one. That's one more example to point out that the current behaviour is not intuitive (and Puppet logs states that local_cups is being installed, but in reality it installs cups).

However, one option is that we don't touch the old behaviour, but we document that module name must start with ${prefix} and maybe we could even add a check for that. I think it is not easy to add ${prefix} to module files automatically.

**Comment by ncsutmf** [comment]
@toddnni I agree, documentation may be the best way around the issue for now.  The only way I can think of to add the prefix automatically would be to use a template to generate the .te file instead of using the source parameter.  However, that is a major change to the defined type and would require some work to make sure all of the possible options are accounted for, and at least initially would need to keep the old behavior and allow the "source" parameter.  If I end up getting some time, I may be able to look into that option.

**Comment by andrewfraley** [comment]
I just ran into this as well.  I'd vote to get rid of the auto prefix completely and use exactly what has been specified for the name.

**Comment by edestecd** [comment]
Yea this prefix stuff is bad news.
In Centos 7.3 the file name must match the module name...
